### ISSUE TITLE
Database Freshness Question

### ISSUE THREAD

**Issue by avimar** [willscott/ip2country#5]
Hi -- I'm using this along with https://github.com/Bluefieldscom/intl-tel-input to provide the pre-selected country.
They had a demo using http://ipinfo.io but that doesn't include HTTPS calls for free.
So I'm here.
It seems other packages https://github.com/eagereyes/node-ip2cc and https://github.com/cmfatih/iptocountry/ rely on WEBNet77 but either you have to manually rebuild frequently or the second one has sync loading methods...

Since I only would like the country code and not any more advanced information, how accurate do you think this database is? How "stale" might it get and what is your update policy for the pre-distributed information?
Oh. Or is ipv4 almost exhausted, so country codes probably won't change much..?

Thanks for any information!

**Comment by willscott** [comment]
There's a cron job running a weekly `grunt build bump publish` every monday morning.

There are regular changes to routing tables, but much less change of country codes associated with IPs - most of the change in announcements is prioritization of different paths in reaction to congestion or link failures.

The database will be reasonably accurate for end users. It will do less well for infrastructure (for instance, all google servers will be considered "US")
