### ISSUE TITLE
Update list with a new publish

### ISSUE THREAD

**Issue by Bilb** [willscott/ip2country#7]
Hi @willscott 
Currently using this in my project, thank you for that !

We have a few ips marked as unknown and I was wondering if you could just publish a new version for that mapping to be updated?
Otherwise I will get a new version on my side but the latest publish date is from 5 years ago already.

Thanks a lot

**Comment by willscott** [comment]
I published a current version.

I haven't set up any automation on this, but if it's useful i'd have no problem with a github action set up to periodically republish the table with an updated version.
